config/routes.rb
DukeApp::Application.routes.draw do
    

  resources :phoneuploads do as_routes end
  
  post 'app_install/phoneupload' => 'phoneuploads#create'

  resources :payloads do as_routes end
  resources :downloads do as_routes end
  resources :sessions do as_routes end
  resources :users do as_routes end
  resources :admins do as_routes end
    
  get 'app_install/install_parkduke'
  get 'app_install/small_image_parkduke'
  get 'app_install/large_image_parkduke'
  get 'app_install/ipa_parkduke'

  get 'app_install/install_wearduke'
  get 'app_install/small_image_wearduke'
  get 'app_install/large_image_wearduke'
  get 'app_install/ipa_wearduke'

  get 'app_install/install_reengage'
  get 'app_install/small_image_reengage'
  get 'app_install/large_image_reengage'
  get 'app_install/ipa_reengage'

  get 'app_install/install_wearduketest'
  get 'app_install/install_wearduketest'
  get 'app_install/small_image_wearduketest'
  get 'app_install/large_image_wearduketest'
  get 'app_install/ipa_wearduketest'

  get 'app_install/install_s2k'
  get 'app_install/small_image_s2k'  
  get 'app_install/large_image_s2k'
  get 'app_install/ipa_s2k'

  get 'app_install/install_dukedoor'
  get 'app_install/small_image_dukedoor'
  get 'app_install/large_image_dukedoor'
  get 'app_install/ipa_dukedoor'
  
    
  get 'install_plist' => 'home#install_plist'
  get 'install_ipa' => 'home#install_ipa'
  get 'install' => 'home#install_ipa'      
      
  get "administration/index"
  
  get "home/index"
  match 'home/logout'=>'home#logout'
  get 'home/log_the_parkduke_app_install'
  get 'home/log_the_wearduke_app_install'
  get 'home/log_the_reengage_app_install'
  get 'home/log_the_wearduketest_app_install'
  get 'home/log_the_s2k_app_install'
  get 'home/log_the_dukedoor_app_install'
  
  get 'debug' => 'home#debug'

  root :to => 'home#index'

end

app/models/phoneupload.rb
class Phoneupload < ActiveRecord::Base
  attr_accessible :uploadfile, :sha1hash
  mount_uploader :uploadfile, UploadfileUploader
  
  before_validation :check_sha1_hash , :on => :create

  require 'digest/sha1'
  
  def compute_sha1_hash
      hash = Digest::SHA1.new
      open("#{self.uploadfile}", 'r') do |io|
        until io.eof?
          buffer = io.read(1024)
          hash.update(buffer)
        end
      end
      # return hash.base64digest
      return hash.hexdigest   
  end

  def check_sha1_hash
    @the_hash = compute_sha1_hash
    if @the_hash == self.sha1hash
      return true
    else
      errors.add(:ERROR, "SHA1 hash #{self.sha1hash} sent with file does not match hash #{@the_hash} calculated on file received at server: #{@the_hash}")
      return false
    end
  end
           
end

app/controllers/phoneuploads_controller.rb
class PhoneuploadsController < ApplicationController
  
  ##############
  # generally we assume that apps will be programatically posting files here
  # instead of users visiting the web pages, so this is mostly a REST-style interface
  # You can validate that this works via a CURL command something like this:
  #
  #      curl -X POST \
  #        -H "Content-Type: multipart/form-data" \
  #        -H "Accept: application/json"
  #        --form "sha1hash=put-the-hash-for-the-file-here" \
  #        --form "uploadfile=@filname.zip" \
  #        http://localhost:3000/phoneuploads
  #
  # the json returned will look like this:
  #
  #     [{"status":"OK"},{"created_at":"2016-06-05T21:38:41Z"}]
  #
  #  or like this in the event of a failure:
  #
  #     [{"status":"ERROR"},
  #          {"ERROR":["SHA1 hash 36454383da993f976f5c22e6d73856f46c2ec044 sent with file does 
  #                     not match hash calculated on file received at server:
  #                     36454383da993f976f5c22e6d73856f46c2ec045"]
  #           }]
  #
  # this consistency checking on the SHA-1 hash of the file happens before it is saved
  # on the server, so you cannot upload without a valid hash, and we have some assurance
  # that the file arrived without damage.
  #############
  
  
  # GET /phoneuploads/new
  # GET /phoneuploads/new.json
  def new
    @phoneupload = Phoneupload.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phoneupload }
    end
  end


  # POST /phoneuploads
  # POST /phoneuploads.json
  def create
    @phoneupload = Phoneupload.new({:sha1hash => params[:sha1hash], :uploadfile => params[:uploadfile]})

    respond_to do |format|
      if @phoneupload.save
        Session.create(:action => 'phoneupload-OK', :netid => '', :notes => "#{@phoneupload.sha1hash} - #{@phoneupload.uploadfile}")
        format.html { redirect_to @phoneupload, notice: 'Phoneupload was successfully created.' }
        format.json { render json: [{:status => 'OK'}, :created_at => @phoneupload.created_at], status: :created }
#        format.json { render json: @phoneupload, status: :created, location: @phoneupload }
      else
        Session.create(:action => 'phoneupload-ERROR', :netid => '', :notes => "#{@phoneupload.errors.first} - #{@phoneupload.uploadfile}")
        format.html { render action: "new" }
        format.json { render json: [{:status => 'ERROR'}, @phoneupload.errors], status: :unprocessable_entity }      
#        format.json { render json: @phoneupload.errors, status: :unprocessable_entity }
      end
    end
  end
  
  #############################################################
  # need to fix this to limit the vewing of previously uploaded stuff to admins only
  # but in the interests of getting the iOS developer working doing their
  # uploads we will not bother right now
  #
  # this should be limit access to everything except uploads to the app admins
  # so - everything below this line is app admin only
  #############################################################
  
  #before_filter :onlyAdmin  
  layout 'admin_base'
  
  active_scaffold :"phoneupload" do |conf|
    conf.actions = [:list, :search, :show, :delete]
    active_scaffold_config.search.live = true   #submit search terms as we type for more feedback
    conf.list.sorting = { :id => :desc}
    
    conf.columns = [ :id, :sha1hash, :uploadfile, :updated_at, :created_at ] 
    conf.columns[:sha1hash].label = "SHA-1 hash"      
    conf.columns[:id].label = "id"      
    conf.columns[:uploadfile].label = "file"      
  end

	# Override authorize in application_controller.rb
  def authorize
    case request.format
    when Mime::JSON
      return true
    else
      super
    end
  end


end

app/helpers/phoneuploads_helper.rb
module PhoneuploadsHelper
end

app/views/phoneuploads/_form.html.erb
<%= form_for @phoneupload, html: { multipart: true } do |f| %>
  <% if @phoneupload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phoneupload.errors.count, "error") %> prohibited this phoneupload from being saved:</h2>

      <ul>
      <% @phoneupload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sha_1_hash %><br />
    <%= f.text_field :sha1hash %>
  </div>
  <div class="field">
    <%= f.label :File_to_upload %><br />
    <%= f.file_field :uploadfile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phoneuploads/index.html.erb
<h1>Listing phoneuploads</h1>

<table>
  <tr>
    <th>SHA-1 hash</th>
	<th></th>
    <th>Uploadfile</th>
    <th></th>
    <th></th>
  </tr>

<% @phoneuploads.each do |phoneupload| %>
  <tr>
    <td><%= phoneupload.sha1hash %></td>
	<th></th>
    <td><%= phoneupload.uploadfile %></td>
    <td><%= link_to 'Show', phoneupload %></td>
    <td><%= link_to 'Destroy', phoneupload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phoneupload', new_phoneupload_path %>

app/views/phoneuploads/new.html.erb
<h1>New phoneupload</h1>

<%= render 'form' %>

<%= link_to 'Back', phoneuploads_path %>

app/views/phoneuploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>SHA-1 hash:</b>
  <%= @phoneupload.sha1hash %>
</p>

<p>
  <b>Uploadfile:</b>
  <%= @phoneupload.uploadfile %>
</p>


<%= link_to 'Back', phoneuploads_path %>