config/routes.rb
DukeApp::Application.routes.draw do
    

  resources :phoneuploads do as_routes end
  
  post 'app_install/phoneupload' => 'phoneuploads#create'

  resources :payloads do as_routes end
  resources :downloads do as_routes end
  resources :sessions do as_routes end
  resources :users do as_routes end
  resources :admins do as_routes end
    
  get 'app_install/install_parkduke'
  get 'app_install/small_image_parkduke'
  get 'app_install/large_image_parkduke'
  get 'app_install/ipa_parkduke'

  get 'app_install/install_wearduke'
  get 'app_install/small_image_wearduke'
  get 'app_install/large_image_wearduke'
  get 'app_install/ipa_wearduke'

  get 'app_install/install_reengage'
  get 'app_install/small_image_reengage'
  get 'app_install/large_image_reengage'
  get 'app_install/ipa_reengage'

  get 'app_install/install_wearduketest'
  get 'app_install/install_wearduketest'
  get 'app_install/small_image_wearduketest'
  get 'app_install/large_image_wearduketest'
  get 'app_install/ipa_wearduketest'

  get 'app_install/install_s2k'
  get 'app_install/small_image_s2k'  
  get 'app_install/large_image_s2k'
  get 'app_install/ipa_s2k'

  get 'app_install/install_dukedoor'
  get 'app_install/small_image_dukedoor'
  get 'app_install/large_image_dukedoor'
  get 'app_install/ipa_dukedoor'
  
    
  get 'install_plist' => 'home#install_plist'
  get 'install_ipa' => 'home#install_ipa'
  get 'install' => 'home#install_ipa'      
      
  get "administration/index"
  
  get "home/index"
  match 'home/logout'=>'home#logout'
  get 'home/log_the_parkduke_app_install'
  get 'home/log_the_wearduke_app_install'
  get 'home/log_the_reengage_app_install'
  get 'home/log_the_wearduketest_app_install'
  get 'home/log_the_s2k_app_install'
  get 'home/log_the_dukedoor_app_install'
  
  get 'debug' => 'home#debug'

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout "home"
  
  def index
  end
  
  def logout
     reset_session
     return_to_me = "?returnto=" + url_for(:controller=>'home')
     redirect_to "/Shibboleth.sso/Logout?return=https://shib.oit.duke.edu/cgi-bin/logout.pl" +
       CGI.escape(return_to_me)
   end

   def log_the_parkduke_app_install
     # write an entry to the sessions table
     Session.create(:action => 'Install-ParkDuke', 
                    :netid => "#{@netid}", 
                    :notes => "#{request.env['REMOTE_ADDR']} - #{request.env['HTTP_USER_AGENT']} ")
    
     @http_server_type = 'https'
     if ENV['RAILS_ENV'] == 'development' # during dev we are not on an https server...
       @http_server_type = 'http' 
     end
    
     # now send them off to get the manifest
     redirect_to "itms-services://?action=download-manifest&amp;url=#{@http_server_type}://#{request.env['HTTP_HOST']}/app_install/install_parkduke"         
   end

   def log_the_wearduke_app_install
     # write an entry to the sessions table
     Session.create(:action => 'Install-WearDuke', 
                    :netid => "#{@netid}", 
                    :notes => "#{request.env['REMOTE_ADDR']} - #{request.env['HTTP_USER_AGENT']} ")
    
     @http_server_type = 'https'
     if ENV['RAILS_ENV'] == 'development' # during dev we are not on an https server...
       @http_server_type = 'http' 
     end
    
     # now send them off to get the manifest
     redirect_to "itms-services://?action=download-manifest&amp;url=#{@http_server_type}://#{request.env['HTTP_HOST']}/app_install/install_wearduke"         
   end

   def log_the_wearduketest_app_install
     # write an entry to the sessions table
     Session.create(:action => 'Install-WearDukeTest', 
                    :netid => "#{@netid}", 
                    :notes => "#{request.env['REMOTE_ADDR']} - #{request.env['HTTP_USER_AGENT']} ")
    
     @http_server_type = 'https'
     if ENV['RAILS_ENV'] == 'development' # during dev we are not on an https server...
       @http_server_type = 'http' 
     end
    
     # now send them off to get the manifest
     redirect_to "itms-services://?action=download-manifest&amp;url=#{@http_server_type}://#{request.env['HTTP_HOST']}/app_install/install_wearduketest"         
   end

   def log_the_reengage_app_install
     # write an entry to the sessions table
     Session.create(:action => 'Install-ReEnage', 
                    :netid => "#{@netid}", 
                    :notes => "#{request.env['REMOTE_ADDR']} - #{request.env['HTTP_USER_AGENT']} ")
    
     @http_server_type = 'https'
     if ENV['RAILS_ENV'] == 'development' # during dev we are not on an https server...
       @http_server_type = 'http' 
     end
    
     # now send them off to get the manifest
     redirect_to "itms-services://?action=download-manifest&amp;url=#{@http_server_type}://#{request.env['HTTP_HOST']}/app_install/install_reengage"         
   end

   def log_the_s2k_app_install
     # write an entry to the sessions table
     Session.create(:action => 'Install-s2k', 
                    :netid => "#{@netid}", 
                    :notes => "#{request.env['REMOTE_ADDR']} - #{request.env['HTTP_USER_AGENT']} ")
    
     @http_server_type = 'https'
     if ENV['RAILS_ENV'] == 'development' # during dev we are not on an https server...
       @http_server_type = 'http' 
     end
    
     # now send them off to get the manifest
     redirect_to "itms-services://?action=download-manifest&amp;url=#{@http_server_type}://#{request.env['HTTP_HOST']}/app_install/install_s2k"         
   end

   def log_the_dukedoor_app_install
     # write an entry to the sessions table
     Session.create(:action => 'Install-DukeDoor', 
                    :netid => "#{@netid}", 
                    :notes => "#{request.env['REMOTE_ADDR']} - #{request.env['HTTP_USER_AGENT']} ")
    
     @http_server_type = 'https'
     if ENV['RAILS_ENV'] == 'development' # during dev we are not on an https server...
       @http_server_type = 'http' 
     end
    
     # now send them off to get the manifest
     redirect_to "itms-services://?action=download-manifest&amp;url=#{@http_server_type}://#{request.env['HTTP_HOST']}/app_install/install_dukedoor"         
   end

   
   def install_plist
     file_path = "#{Rails.root}/public/testing/Example.plist"
     send_file file_path, :filename => params[:filename], :disposition => 'attachment'     
   end

   def install_ipa
     file_path = "#{Rails.root}/public/testing/Example.ipa"
     send_file file_path, :filename => params[:filename], :disposition => 'attachment'     
   end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/debug.html.erb
<h2>DukeApps Debug Page</h2>
<b>Debug</b>

<p><b>ENV['RAILS_ENV']</b><br><%=ENV['RAILS_ENV']%></p>
<hr>
<p><b>server</b> : <%=request.env['HTTP_HOST']%></p> 
<p><b>@this_user.netid</b> : <%=@this_user.netid%></p>
<p><b>@this_user.duid</b> : <%=@this_user.duid%></p>
<p><b>@this_user.displayName</b> : <%=@this_user.displayName%></p>

<hr>
<p><b>request.env</b><br><%=request.env%></p>
<hr>

app/views/home/index.html.erb
<div class="textwidget">
	<h3>About DukeApps</h3>
	<p>Authorized users can install Duke-specific mobile applications from this site</p>
</div>
<% if session[:parkduke_people] %>
   <p><div class="widget_text">
   	  <%= link_to home_log_the_parkduke_app_install_path do %>
   	     <%= image_tag("/app_install/small_image_parkduke", :size => "58x58", :alt => "ParkDuke") %>
   	     &nbsp; install ParkDuke
   	  <% end %>
     </div>
   </p>
<% end %>
<% if session[:reengage_people] %>
     <p><div class="widget_text">
   	    <%= link_to home_log_the_reengage_app_install_path do %>
   	      <%= image_tag("/app_install/small_image_reengage", :size => "58x58", :alt => "SymMon") %>
   	      &nbsp; install SymMon
   	    <% end %>
      </div>
   </p>
<% end %>
<% if session[:wearduke_people] %>
     <p><div class="widget_text">
   	    <%= link_to home_log_the_wearduke_app_install_path do %>
   	      <%= image_tag("/app_install/small_image_wearduke", :size => "58x58", :alt => "WearDuke") %>
   	      &nbsp; install WearDuke
   	    <% end %>
      </div>
   </p>
<% end %>
<% if session[:wearduketest_people] %>
     <p><div class="widget_text">
   	    <%= link_to home_log_the_wearduketest_app_install_path do %>
   	      <%= image_tag("/app_install/small_image_wearduketest", :size => "58x58", :alt => "WearDukeTest") %>
   	      &nbsp; install WearDukeTest
   	    <% end %>
      </div>
   </p>
<% end %>
<% if session[:s2k_people] %>
     <p><div class="widget_text">
   	    <%= link_to home_log_the_s2k_app_install_path do %>
   	      <%= image_tag("/app_install/small_image_s2k", :size => "58x58", :alt => "s2k") %>
   	      &nbsp; install s2k
   	    <% end %>
      </div>
   </p>
<% end %>

<p><div class="widget_text">
	<%= link_to home_log_the_dukedoor_app_install_path do %>
	  <%= image_tag("/app_install/small_image_dukedoor", :size => "58x58", :alt => "Duke Door") %>
	  &nbsp; install Duke Door
	<% end %>
  </div>
</p>
</div>