config/routes.rb
DukeApp::Application.routes.draw do
    

  resources :phoneuploads do as_routes end
  
  post 'app_install/phoneupload' => 'phoneuploads#create'

  resources :payloads do as_routes end
  resources :downloads do as_routes end
  resources :sessions do as_routes end
  resources :users do as_routes end
  resources :admins do as_routes end
    
  get 'app_install/install_parkduke'
  get 'app_install/small_image_parkduke'
  get 'app_install/large_image_parkduke'
  get 'app_install/ipa_parkduke'

  get 'app_install/install_wearduke'
  get 'app_install/small_image_wearduke'
  get 'app_install/large_image_wearduke'
  get 'app_install/ipa_wearduke'

  get 'app_install/install_reengage'
  get 'app_install/small_image_reengage'
  get 'app_install/large_image_reengage'
  get 'app_install/ipa_reengage'

  get 'app_install/install_wearduketest'
  get 'app_install/install_wearduketest'
  get 'app_install/small_image_wearduketest'
  get 'app_install/large_image_wearduketest'
  get 'app_install/ipa_wearduketest'

  get 'app_install/install_s2k'
  get 'app_install/small_image_s2k'  
  get 'app_install/large_image_s2k'
  get 'app_install/ipa_s2k'

  get 'app_install/install_dukedoor'
  get 'app_install/small_image_dukedoor'
  get 'app_install/large_image_dukedoor'
  get 'app_install/ipa_dukedoor'
  
    
  get 'install_plist' => 'home#install_plist'
  get 'install_ipa' => 'home#install_ipa'
  get 'install' => 'home#install_ipa'      
      
  get "administration/index"
  
  get "home/index"
  match 'home/logout'=>'home#logout'
  get 'home/log_the_parkduke_app_install'
  get 'home/log_the_wearduke_app_install'
  get 'home/log_the_reengage_app_install'
  get 'home/log_the_wearduketest_app_install'
  get 'home/log_the_s2k_app_install'
  get 'home/log_the_dukedoor_app_install'
  
  get 'debug' => 'home#debug'

  root :to => 'home#index'

end

app/views/layouts/admin_base.html.erb
<% content_for :navbar do %>
	<%= render template: 'layouts/admin_menu'%>
<% end %>
<%= render :template => 'layouts/base' %>

app/views/layouts/admin_menu.html.erb
<div>
	<ul class="nav nav-tabs">
	  <li role="presentation" <% if params[:controller] == "admins" %>class="active"<% end %> >
			<%= link_to "Admins", admins_path %> 
		</li>
	  <li <% if params[:controller] == 'users' %>class="active"<% end %> >
			<%= link_to "Users", '/users' %>
	   </li>
	  <li <% if params[:controller] == 'sessions' %>class="active"<% end %> >
			<%= link_to "Sessions", '/sessions' %>
	   </li>
	  <li <% if params[:controller] == 'downloads' %>class="active"<% end %> >
			<%= link_to "Downloads", '/downloads' %>
	   </li>
	  <li <% if params[:controller] == 'phoneuploads' %>class="active"<% end %> >
			<%= link_to "Phoneuploads", '/phoneuploads' %>
	   </li>
	  <li <% if params[:controller] == 'payloads' %>class="active"<% end %> >
			<%= link_to "Payloads", '/payloads' %>
	   </li>
	</ul>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DukeApps</title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" /> 
	<meta name="apple-mobile-web-app-capable" content="yes" />
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
	<%= stylesheet_link_tag "style", :media => "all" %>
	
	<%= yield :stylesheets %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Droid+Sans:400,700|Droid+Serif:400,700' rel='stylesheet' type='text/css'>
</head>

<body class="home page page-id-4 page-template-default single-author">
<div id="page" class="hfeed">

<header id="branding" role="banner">
	<div id="logo">
		 <p><a href="http://www.duke.edu" tabindex="1" accesskey="1"><img src="/assets/struct/logo.png" width="141" height="64" alt="Duke University" /></a></p>
     <h1><a href="/" rel="home" tabindex="2" accesskey="2">DukeApps</a></h1>
	<ul id="mmenu">
	  <li <% if params[:controller] == "home" %>class="active"<% end %> >
			<a href='/'>Home</a>
		</li>
		<% if session[:is_admin] %>
	  <li <% if params[:controller] == "administration"  %>class="active"<% end %> >
			<a href='/administration/index'>Admin</a>
		</li>
		<% end %>
		<li class='logout'>
			<a href='/home/logout'>Logout</a>
		</li>
			
	</ul>	
</div>
</header><!-- #branding -->

<div id="content">
<%= yield :meat %>
</div>

<div id="subFooter">
  <ul class="links" id="socialLinks">
    <li><a href="http://futurity.org"><img src="/assets/futurity.gif" /></a></li>
    <li><a href="http://www.youtube.com/duke"><img src="/assets/youtube.gif" /></a></li>
    <li><a href="http://twitter.com/DukeNews"><img src="/assets/twitter.gif" /></a></li>
    <li><a href="http://www.facebook.com/DukeUniv"><img src="/assets/facebook.gif" /></a></li>
    <li><a href="http://itunes.duke.edu/"><img src="/assets/apple.gif" /></a></li>
    <li><a href="http://news.duke.edu/"><img src="/assets/rss.gif" /></a></li>
  </ul>
<ul class="links" id="subFootLinks"><li class="menu-334 first"><a href="http://www.access.duke.edu/" title="">Accessibility</a></li>
  <li class="menu-115"><a href="http://duke.edu/styleguide.html" title="">Style Guide</a></li>
  <li class="menu-293"><a href="http://duke.edu/about_this_site.html" title="">About Duke.edu</a></li>
  <li class="menu-116 last"><a href="http://oit.duke.edu/about/contact/index.php" title="">Contact Us</a></li>
</ul>
    <a href="http://www.duke.edu" id="subFootLogo">Duke University</a>
    <p>&copy; 2012-2016 Duke University, Durham, NC 27708 | (919) 684-8111</p>    
</div>

</body>
</html>

app/views/layouts/base.html.erb
<% content_for :meat do %>
	<div id="pagewrapper">
		<div class="entry-content">
			<div id='message_area' style='clear:both;'>
				<% flash.each do |name, msg| -%>
					<%= content_tag :div, msg, class: name %>
		    <% end -%>
			</div>
			<%= yield :navbar%>
			<%= yield %>
  		<div class="clear"></div>
<% end %>

<%= render :template => 'layouts/application' %>

app/views/layouts/home.html.erb
<% content_for :meat do %>
	<div id="main" class="clearfix">
		<div id="mask"></div>

			<div id="primary" class="full-width">
				<div id="content" role="main">
					<div class="front-page">	    
						<div class="clearfix">
							<% flash.each do |name, msg| -%>
							      <%= content_tag :div, msg, class: name %>
							    <% end -%>
									<div class="entry-content">
<%= yield %>


            </div><!--! end of .clearfix -->
					</div><!--! end of .front-page -->
				</div><!-- #content -->
			</div><!-- #primary -->
		</div><!-- #main -->


<% end %>


<%= render :template => 'layouts/application' %>

app/views/layouts/minimalist.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DukeApps</title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
	
<%= yield :meat %>


</body>
</html>